### ISSUE TITLE
Minor: Create2 Deployments

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/portfolio#202]
# Description
If we can get a deterministic deployment for Hyper, it will be much easier to maintain all the tools that use help us interact with the protocol. Since we only have one contract, we can just pass in a salt on deployment, right?

**Comment by clemlak** [comment]
I started working on a new script using `create3` to deploy the contracts, so the address of the Registry and the RMM01 contracts will be the same everywhere (cf https://github.com/primitivefinance/portfolio/tree/experiment/create3).

**Comment by clemlak** [comment]
- [ ] TODO: Make our own `create3` factory so we can  deploy our contracts wherever we want.

**Comment by Alexangelj** [comment]
Done with the repository: https://github.com/primitivefinance/nugu
