### ISSUE TITLE
Useless amount pointer in `encodeSwap`

### ISSUE THREAD

**Issue by clemlak** [primitivefinance/portfolio#239]
The `endodeSwap` function is using an extra variable to point where the amount1 starts, however since we are using static types, the value of the pointer will always be the same (proof: it's even hardcoded right now). 

I suggest we should get rid of it.

Cf: https://github.com/primitivefinance/hyper/blob/1.0.0-beta/contracts/libraries/EnigmaLib.sol#L224

**Comment by clemlak** [comment]
Not closing this because this branch (https://github.com/primitivefinance/portfolio/commits/feat/mega) is actually bringing back pointers, both for the `decodeSwap` and `decodeClaim`.

**Comment by Alexangelj** [comment]
Can close right?
