### ISSUE TITLE
Fix: getVirtualPrice is incorrectly named

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/portfolio#298]
# Description
The `getVirtualPrice` function is a semi-standardized way to let frontends query the price of one unit of a liquidity share. The implementation in Portfolio returns the REPORTED SPOT PRICE of the `asset` token. This could potentially mislead anyone who integrates Portfolio.

**Comment by clemlak** [comment]
Would simply renaming the function to `getSpotPrice` work?

**Comment by clemlak** [comment]
Done here https://github.com/primitivefinance/portfolio/tree/feat/add-getSpotPrice.

**Comment by clemlak** [comment]
Closing this since the PR was merged.
