### ISSUE TITLE
Fix: chaining create pool and allocate can lead to failed transactions

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/portfolio#299]
# Description
Allocate takes a `poolId` argument, but if a pool is being created then the calldata must be constructed using a predicted `poolId`. For example, if we are creating a pool, we can assume that the next poolId will have a `poolNonce + 1` in the last 4 bytes. However, if a pool is created for the same pair while this transaction is in the mempool, it will use the created pool in the other transaction instead of the user's desired pool. 

To fix this, a `0` poolId can be used to signal to allocate to use the most recent poolNonce. This is how it's handled in `createPool` if we want to use the most recently created pair.

**Comment by ts0yu** [comment]
going to take this

**Comment by clemlak** [comment]
I took a different approach to fix this, see https://github.com/primitivefinance/portfolio/pull/364.
