### ISSUE TITLE
Fix: Forced to withdraw tokens to wallet via minimum two transactions

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/portfolio#334]
# Description
After the `multiprocess` function completes any leftover balances are applied as credits to the `msg.sender`'s internal balance. This forces the `msg.sender` to broadcast another transaction calling `draw` to withdraw their tokens to their wallet address: `msg.sender`.

# Changes
- In the settlement function, transfer (via token.transfer method) `credit` amount of tokens to `msg.sender` instead of applying the credit to their balance.

**Comment by clemlak** [comment]
Closing this issue since it was fixed and merged.
