### ISSUE TITLE
Fix: state usage is expensive

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/portfolio#347]
In the `_swap` function we use a private state variable to track some information: https://github.com/primitivefinance/portfolio/blob/78626766edc3e6282fbc013e6c15285b19a2bd72/contracts/Portfolio.sol#L360-L371

Using state, even though its deleted by the end of the function, has only a small gas refund. If this can be put into memory and still be under the contract size limit, it could decrease the cost to swap.

**Comment by clemlak** [comment]
This branch (https://github.com/primitivefinance/portfolio/tree/fix/state-usage) fixes this but can trigger a `stack too deep error` (even using `--via-ir`) depending on the parameters of the compiler.

**Comment by Alexangelj** [comment]
Fixed in #372
