### ISSUE TITLE
Fix: swap event feeAmount argument is using the wrong value

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/portfolio#350]
See https://github.com/primitivefinance/portfolio/blob/a2a43a9fb9097e6129b6b20634d3e8e44745eedd/contracts/Portfolio.sol#L522

Incorrectly setting `feeAmount`, which gets emitted in the Swap event, to the a double scaled down `iteration.input` value. This line needs to be updated to `feeAmount`.

**Comment by clemlak** [comment]
Closing this as it's now fixed.
