### ISSUE TITLE
Fix: duration of pools can be the max duration for perpetual and non-perpetual pools

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/portfolio#353]
# Description
A perpetual pool has a constant duration of 500. A non-perpetual pool can be created with a duration of 500. This can lead to some confusion

**Comment by clemlak** [comment]
TODO:
- [ ] Remove the `isPerpetual` bool and store the max value of the duration variable instead.

**Comment by clemlak** [comment]
PR was merged.
