### ISSUE TITLE
Incorrect getSpotPrice

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/portfolio#436]
https://github.com/primitivefinance/portfolio/blob/47d1e0bc32d261b197bfa989befe0ad039188351/contracts/strategies/NormalStrategyLib.sol#L414

If x has reached its upper bound, it should return a 0 price.

**Comment by Autoparallel** [comment]
On it!

**Comment by Alexangelj** [comment]
Note that is function is not relied upon in the codebase, it's only exposed to make it easier to get information from the pool.
