### ISSUE TITLE
Consider a wider range of fee values in Portfolio (e.g., below 1bps)

### ISSUE THREAD

**Issue by 0xJepsen** [primitivefinance/portfolio#446]
Portfolio has a fee parameter win a minimum of 1bps. It would be a good idea to revisit this. Give's us more analysis capabilities as well.

**Comment by 0xJepsen** [comment]
Down to the 1/100 of a bp

**Comment by Autoparallel** [comment]
Why not even just allow extremely small fees and use a wad value?

**Comment by 0xJepsen** [comment]
Done locally

**Comment by 0xJepsen** [comment]
Maybe this is portfolio V2 feature
